[package]
name = "rusty-ships"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
live2d-cubism-core-sys = { git = "https://github.com/James2022-rgb/live2d-cubism-core-sys" }
glium = "0.32.1"
image = "0.24.7"
serde = { verson = "1.0.188", features = ["derive"]}
serde_json = "1.0.105"
